### ISSUE TITLE
契約書の英文と和文のテキスト原稿

### ISSUE THREAD

**Issue by heppokofrontend** [Kiryu-kai/semi-permanent-contract#1]
契約書ページに掲載したく、元原稿をテキストベースでご連携いただけないでしょうか。

**Comment by sameKRKIHSYM** [comment]
JP
桐生会　たつのこ半永久的継続契約書


この契約書に署名するとホロライブ四期生 桐生ココ様が運営する
「桐生会」及び「たつのこ」に半永久的に（勝手に）任命します。

この契約書に署名者は以下のことを認めます。
・「桐生会」及び「たつのこ」に半永久的になります。
・桐生会4代目会長 桐生ココ様へのガチ恋を認めます。
・いつまでも桐生会4代目会長 桐生ココ様を布教し続けます。
・いつでも自分が桐生会であるという自覚をもって桐生会として恥ずかしくない行動を心がけます。

正装は「クソザコＴ」or「ガチコイＴ」に桐生会代紋です。
外出の際には必ず桐生会代紋を身に着けるようにしてください。
※８月１６日以後に桐生会代紋スマホケースが届いたときには外出の際スマートフォンを持っていく場合は桐生会代紋スマホケースを必ず装着した状態でスマートフォンを使用してください。

※この契約書の有効期限は西暦2021年7月1日から2521年7月1日までです。
2521年7月1日にまた桐生会4代目会長 桐生ココ様のもとへ自分から訪れて”必ず”更新をしてください。

**Comment by sameKRKIHSYM** [comment]
EN
[Kiryu-kai] Tatsunoko Semi-Permanent Contract

Those who sign this contract are appointed (appoint themselves) as semi-permanent members titled “tatsunoko” of the organization Kiryu-kai as headed by Kiryu Coco-sama, Hololive 4th Gen.

By signing this contract, you acknowledge the following:
- You become semi-permanent members of Kiryu-kai as tatsunoko.
- You acknowledge you are gachikoi towards Kiryu Coco-sama, the Fourth Generation Chairman of Kiryu-kai.
- You will continue evangelizing about Kiryu Coco-sama, the Fourth Generation Chairman of Kiryu-kai.
- You promise to always be aware of your identity as a member of Kiryu-kai and to carry yourself in a way that does not bring shame to the organization.

The official uniform is a Kiryu-kai Daimon Pin together with either a Kusozako T-Shirt or a Gachikoi T-Shirt.
Always remember to bear the Kiryu-kai Daimon Pin whenever out in public.
※ After you receive your shipment of the Kiryu-kai Daimon Smartphone Case after August 16, 2021, always remember to store your smartphone within your Kiryu-kai Daimon Smartphone Case whenever out in public.

※ This contract is effective from July 1, 2021 until July 1, 2521. Make sure to visit Kiryu Coco-sama, the Fourth Generation Chairman of Kiryu-kai, on July 1, 2521 to renew this contract in person.

**Comment by heppokofrontend** [comment]
@sameKRKIHSYM ありがとうございます！！！助かりました！！
